// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnVq5KdNwAY6af0Iaq4yYAs8yGNj102cw',
    appId: '1:127499814071:web:52a45f33e970a4c9eb7932',
    messagingSenderId: '127499814071',
    projectId: 'request-live-riverpods',
    authDomain: 'request-live-riverpods.firebaseapp.com',
    storageBucket: 'request-live-riverpods.appspot.com',
    measurementId: 'G-3K52EDHYFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE862dnRmHNl7AE5g0BU79izXePK9rsf8',
    appId: '1:127499814071:android:2e43f3d6df63c18beb7932',
    messagingSenderId: '127499814071',
    projectId: 'request-live-riverpods',
    storageBucket: 'request-live-riverpods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS2Ljx4BCWVAbIrjU3PBzOD5Vu6SYZh5U',
    appId: '1:127499814071:ios:277e2afe80b080d4eb7932',
    messagingSenderId: '127499814071',
    projectId: 'request-live-riverpods',
    storageBucket: 'request-live-riverpods.appspot.com',
    iosClientId:
        '127499814071-htmd06oot8un9vrom7uk04ociod4v3rq.apps.googleusercontent.com',
    iosBundleId: 'com.derekdileo.requestLiveRiverpods',
  );
}
